sonar.projectKey=Danieldiazi_homeassistant-meteogalicia
sonar.organization=danieldiazi
sonar.sources=custom_components/meteogalicia
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.14
sonar.sourceEncoding=UTF-8
