name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v2

      - name: Create token_extractor.zip
        run: |
          zip homeassistant-meteogalicia.zip -r ./custom_components/
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: homeassistant-meteogalicia.zip
          asset_name: homeassistant-meteogalicia.zip
          tag: ${{ github.ref }}
          overwrite: true
