name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v3

      - name: Create token_extractor.zip
        run: |
          cd custom_components/meteogalicia
          zip homeassistant-meteogalicia.zip -r ./custom_components/meteogalicia/
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: homeassistant-meteogalicia.zip
          asset_name: homeassistant-meteogalicia.zip
          tag: ${{ github.ref }}
          overwrite: true
